services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: morinscode-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - landing
    volumes:
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    networks:
      - web

  landing:
    build:
      context: ./landing
    container_name: morinscode-landing
    expose:
      - "80"
    networks:
      - web

  certbot:
    image: certbot/certbot:latest
    container_name: morinscode-certbot

    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

networks:
  web:
    name: morinscode-web
