services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: morinscode-reverse-proxy
    ports:
      - "8080:80"
    depends_on:
      - landing
    networks:
      - web

  landing:
    build:
      context: ./landing
    container_name: morinscode-landing
    expose:
      - "80"
    networks:
      - web

networks:
  web:
    name: morinscode-web
