events {}

http {
    server {
        listen 80;
        server_name morinscode.dev scoundrels.morinscode.dev;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name morinscode.dev;

        ssl_certificate /etc/letsencrypt/live/morinscode.dev/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/morinscode.dev/privkey.pem;

        location / {
            proxy_pass http://landing:80;
        }
    }

    server {
        listen 443 ssl;
        server_name scoundrels.morinscode.dev;

        ssl_certificate /etc/letsencrypt/live/morinscode.dev/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/morinscode.dev/privkey.pem;

        location / {
            proxy_pass http://scoundrels-frontend:80;
        }
    }
}